USE tempdb
GO

CREATE TABLE TRIVIALPLAN (A INT, B INT, C INT)
GO
CREATE INDEX TRIVIND1 ON TRIVIALPLAN(A)
GO
CREATE CLUSTERED INDEX TRIVCLUS ON TRIVIALPLAN(B)
GO

SET STATISTICS PROFILE ON
GO
INSERT INTO TRIVIALPLAN VALUES (1,2,3)
GO
SET STATISTICS PROFILE OFF
GO



--- DROP UNUSED OBJECTS

DROP TABLE TRIVIALPLAN