:CONNECT NODE1

ALTER AVAILABILITY GROUP [LATENCYDEMO] REMOVE DATABASE [Test_MemoryOptimized]
GO


:CONNECT NODE3
IF EXISTS (SELECT NAME FROM SYS.DATABASES WHERE NAME = 'Test_MemoryOptimized')
BEGIN
	DROP DATABASE [Test_MemoryOptimized]
END

ALTER EVENT SESSION [AlwaysOn_Data_Movement_Tracing] ON SERVER STATE=STOP
GO

:CONNECT NODE2

IF EXISTS (SELECT NAME FROM SYS.DATABASES WHERE NAME = 'Test_MemoryOptimized')
BEGIN
	DROP DATABASE [Test_MemoryOptimized]
END

ALTER EVENT SESSION [AlwaysOn_Data_Movement_Tracing] ON SERVER STATE=STOP
GO

:CONNECT NODE1

USE [Test_MemoryOptimized]
GO

TRUNCATE TABLE  SalesOrderDetail
DELETE FROM  SalesOrderHeader
DELETE FROM  SalesOrderDetail_InMem
DELETE FROM  SalesOrderHeader_InMem

WAITFOR DELAY '00:00:05'

